site_name: 浩哈哈哈哈
theme: 
  name: material
  icon:
    logo: material/noodles
  favicon: https://eng.haohaha.cn/image/favicon.png
  palette:
    - scheme: slate # 夜间模式
      primary: deep purple
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
    - scheme: default # 日间模式
      primary: deep purple # 上方的
      accent: deep orange # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - navigation.expand
    - search.suggest
    - search.highlight
  language: zh

nav:
  - 主页: http://haohaha.cn
  - CS笔记: http://cs.haohaha.cn
  - 闲聊波尔卡: http://chat.haohaha.cn 
  - OS学习: http://os.haohaha.cn
  - 算法打卡: http://alg.haohaha.cn
  - 数学笔记: http://math.haohaha.cn
  - 英语笔记: 
    - Home: index.md
#   - 精读合集: 
#     - 目录: Cata-100.md
#     - 01.1997-01: 1997-01.md
#     - 02.1997-05: 1997-05.md
#     - 03.1999-02: 1999-02.md
#     - 04.1996-03: 1996-03.md
#     - 05.2002-01: 2002-01.md
#     - 06.2002-04: 2002-04.md
#     - 07.2003-01: 2003-01.md
#     - 08.2003-02: 2003-02.md
#     - 09.2003-03: 2003-03.md
#
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
extra_css:
  - mkdocs/css/no-footer.css # 不使用底部的翻页
extra:
  homepage: http://haohaha.cn
  social: # icons
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1436476753
      name: Bilibili | 浩哈哈哈哈 # 鼠标悬浮提示
    - icon: fontawesome/brands/github
      link: https://github.com/Haohahahaha
      name: GitHub | Haohahahaha
    - icon: simple/githubactions
      link: https://github.com/Haohahahaha/eng/actions
      name: GitHub Actions
## [bottom-left corner]
copyright: 
  <a href="https://beian.miit.gov.cn/" target="_blank">冀ICP备2024078994号</a><br/>
  <a href="http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=13020302001386" target="_blank">冀公网安备13020302001386号</a><br/>
  Copyright &copy; 2022-现在 浩哈哈哈哈_ # 左下角的版权声明